import type {
  ToolCatalogEntry,
  ToolRouteProfileInfo,
  ToolScopeTarget,
} from '../../types/tool-policy.js';

export const GLOBAL_DEFAULT_SCOPE_ID = 'global-default';
export const PRIVATE_DEFAULT_SCOPE_ID = 'private-default';

const ALL_ROUTES = ['agent', 'automation'] as const;

function buildCatalogEntry(entry: Omit<ToolCatalogEntry, 'availableRoutes' | 'defaultEnabledByRoute'>): ToolCatalogEntry {
  return {
    ...entry,
    availableRoutes: [...ALL_ROUTES],
    defaultEnabledByRoute: {
      agent: true,
      automation: true,
    },
  };
}

export const TOOL_ROUTE_PROFILES: ToolRouteProfileInfo[] = [
  {
    id: 'agent',
    title: 'Agent 回复',
    description: 'qqbot reply 唯一的工具型回复链路。模型可先走原生 tool loop，最后一跳返回 StructuredReplyV1。',
    note: '仅允许 plugin 房间进入。',
  },
    {
    id: 'automation',
    title: '自动化',
    description: '任务自动化等非 reply 直答链路的工具配置。',
    note: '当前自动化链路通常不会携带这些工具，但策略会保留并可见。',
  },
];

export const TOOL_DEFAULT_SCOPES: ToolScopeTarget[] = [
  {
    scopeKind: 'global_default',
    scopeId: GLOBAL_DEFAULT_SCOPE_ID,
    title: '全局默认',
    description: '所有会话的基础默认值。群聊和私聊都先继承这里。',
  },
  {
    scopeKind: 'private_default',
    scopeId: PRIVATE_DEFAULT_SCOPE_ID,
    title: '私聊默认',
    description: '所有私聊会话的默认值。单个私聊房间可继续覆盖。',
  },
];

export const LEGACY_TOOL_NAME_ALIASES: Record<string, string | null> = {
  built_question: 'question',
  built_user_confirm: 'user_confirm',
  built_user_toast: null,
  web_fetcher: 'web_fetch',
  web_poster: 'web_post',
};

export const TOOL_CATALOG: ToolCatalogEntry[] = [
  buildCatalogEntry({
    toolName: 'question',
    title: '选项提问',
    category: 'builtin',
    description: '让模型向用户抛出 2-4 个明确选项，要求用户在选项之间做决定。',
    compatibility: 'incompatible',
    compatibilityNote: '会把直答链路拉进中间交互，更适合 research/automation，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['user_confirm'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'user_confirm',
    title: '开放式确认',
    category: 'builtin',
    description: '让模型向用户追问、确认或索取开放式补充信息。',
    compatibility: 'incompatible',
    compatibilityNote: '会让模型转向中间交互，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['question'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_read',
    title: '读取文件',
    category: 'file',
    description: '读取磁盘上的文件内容。',
    compatibility: 'incompatible',
    compatibilityNote: '属于 agent 文件操作能力，不应暴露给 agent。',
    hardDependencies: [],
    relatedTools: ['file_list', 'file_grep', 'file_glob'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_write',
    title: '写入文件',
    category: 'file',
    description: '新建或覆盖写入单个文件。',
    compatibility: 'incompatible',
    compatibilityNote: '会将会话变成可修改文件的 agent 工作流，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['file_multi_write', 'file_update', 'file_rename'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_list',
    title: '列出文件',
    category: 'file',
    description: '列出目录下的文件与子目录，可递归遍历。',
    compatibility: 'incompatible',
    compatibilityNote: '属于 agent 浏览工作区能力，不应默认暴露给 agent。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_glob', 'file_grep'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_grep',
    title: '搜索文本',
    category: 'file',
    description: '按正则或关键字在文件中搜索匹配内容。',
    compatibility: 'incompatible',
    compatibilityNote: '用于 agent 检索工作区，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_list', 'file_glob'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_glob',
    title: '匹配文件名',
    category: 'file',
    description: '按 glob 规则匹配文件路径。',
    compatibility: 'incompatible',
    compatibilityNote: '属于 agent 文件检索能力，不适合作为 agent 工具暴露。',
    hardDependencies: [],
    relatedTools: ['file_list', 'file_grep', 'file_read'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_rename',
    title: '重命名文件',
    category: 'file',
    description: '移动或重命名单个文件、目录。',
    compatibility: 'incompatible',
    compatibilityNote: '涉及真实文件修改，不应开放给 agent。',
    hardDependencies: [],
    relatedTools: ['file_write', 'file_update', 'file_multi_rename'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_multi_rename',
    title: '批量重命名',
    category: 'file',
    description: '按模式批量重命名多个文件或目录。',
    compatibility: 'incompatible',
    compatibilityNote: '会放大文件系统副作用，与 agent 明显冲突。',
    hardDependencies: [],
    relatedTools: ['file_rename', 'file_glob'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_multi_write',
    title: '批量写入文件',
    category: 'file',
    description: '一次写入多个文件内容。',
    compatibility: 'incompatible',
    compatibilityNote: '属于强副作用 agent 工具，不适合开放给 agent。',
    hardDependencies: [],
    relatedTools: ['file_write', 'file_update'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'file_update',
    title: '替换文件片段',
    category: 'file',
    description: '在现有文件中查找并替换指定文本片段。',
    compatibility: 'incompatible',
    compatibilityNote: '属于 agent 编辑能力，不应直接给 agent。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_write'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'web_search',
    title: '联网搜索',
    category: 'web',
    description: '通过搜索引擎查询当前网页或现实世界信息。',
    compatibility: 'conditional',
    compatibilityNote: '适合 agent 的后台检索；agent 默认不应开放。',
    hardDependencies: [],
    relatedTools: ['web_browser', 'web_fetch'],
    riskLevel: 'medium',
    source: 'project',
  }),
  buildCatalogEntry({
    toolName: 'web_browser',
    title: '网页浏览器',
    category: 'web',
    description: '打开网页、提取正文、抓取 HTML 或定位页面片段。',
    compatibility: 'incompatible',
    compatibilityNote: '会将模型带入多步网页浏览工作流，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['web_search', 'web_fetch'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'web_fetch',
    title: '抓取网页内容',
    category: 'web',
    description: '直接请求指定网页并返回内容。',
    compatibility: 'incompatible',
    compatibilityNote: '会让会话进入 agent 抓取流程，不适合 agent。',
    hardDependencies: [],
    relatedTools: ['web_search', 'web_browser', 'web_post'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'web_post',
    title: '发送 HTTP POST',
    category: 'web',
    description: '向外部 URL 发送 JSON POST 请求。',
    compatibility: 'incompatible',
    compatibilityNote: '存在明显外部副作用，不适合作为 agent 工具开放。',
    hardDependencies: [],
    relatedTools: ['web_fetch'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'a9pt1r',
    title: '地理编码',
    category: 'geo',
    description: '按城市名称查询经纬度，用于后续天气查询。',
    compatibility: 'conditional',
    compatibilityNote: '适合 agent 的后台辅助查询，agent 默认不应开放。',
    hardDependencies: [],
    relatedTools: ['z9uylx'],
    riskLevel: 'medium',
    source: 'chatluna_runtime',
  }),
  buildCatalogEntry({
    toolName: 'z9uylx',
    title: '天气预报',
    category: 'geo',
    description: '按经纬度查询未来天气预报。',
    compatibility: 'conditional',
    compatibilityNote: '适合 agent 的后台辅助查询，agent 默认不应开放。',
    hardDependencies: ['a9pt1r'],
    relatedTools: ['a9pt1r'],
    riskLevel: 'medium',
    source: 'chatluna_runtime',
  }),
];

export const TOOL_CATALOG_MAP = new Map(TOOL_CATALOG.map((entry) => [entry.toolName, entry]));
