import type { Context } from 'koishi';
import { ensureLegacyMemoryMigrationTables } from './migration.js';

export function ensureMemoryTables(ctx: Context): void {
  ensureLegacyMemoryMigrationTables(ctx);

  ctx.model.extend(
    'memory_user',
    {
      id: 'unsigned',
      userKey: 'string',
      platform: 'string',
      userId: 'string',
      qqNick: { type: 'string', nullable: true },
      avatarUrl: { type: 'string', nullable: true },
      profileUpdatedAt: { type: 'double', nullable: true },
      firstSeenAt: 'double',
      lastSeenAt: 'double',
      readEnabled: 'unsigned',
      writeEnabled: 'unsigned',
    },
    {
      autoInc: true,
      indexes: [['userKey']],
    },
  );

  ctx.model.extend(
    'memory_context',
    {
      id: 'unsigned',
      contextKey: 'string',
      platform: 'string',
      botSelfId: 'string',
      channelType: 'string',
      groupId: { type: 'string', nullable: true },
      channelId: { type: 'string', nullable: true },
      rawContextId: { type: 'string', nullable: true },
      lastExtractedMessageId: { type: 'string', nullable: true },
      lastExtractedAt: { type: 'double', nullable: true },
      lastExtractedHash: { type: 'string', nullable: true },
      firstSeenAt: 'double',
      lastSeenAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['contextKey'], ['platform', 'channelType']],
    },
  );

  ctx.model.extend(
    'memory_extract_cursor',
    {
      id: 'unsigned',
      ownerUserKey: 'string',
      contextKey: 'string',
      conversationId: 'string',
      lastExtractedMessageId: { type: 'string', nullable: true },
      lastExtractedAt: { type: 'double', nullable: true },
      firstSeenAt: 'double',
      updatedAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['ownerUserKey', 'contextKey'], ['conversationId']],
    },
  );

  ctx.model.extend(
    'memory_candidate',
    {
      id: 'unsigned',
      batchId: 'string',
      candidateType: 'string',
      ownerUserKey: 'string',
      contextKey: 'string',
      conversationId: 'string',
      targetSpeakerId: 'string',
      targetSpeakerName: { type: 'string', nullable: true },
      messageIds: { type: 'text', nullable: true },
      evidenceMessageIds: { type: 'text', nullable: true },
      evidenceSpeakerIds: { type: 'text', nullable: true },
      attributionStatus: 'string',
      payload: 'text',
      reviewStatus: 'string',
      sensitivity: 'string',
      suggestedVisibility: 'string',
      finalVisibility: { type: 'string', nullable: true },
      dropReason: { type: 'text', nullable: true },
      providerRoute: 'string',
      rawTextHash: { type: 'string', nullable: true },
      createdAt: 'double',
      reviewedAt: { type: 'double', nullable: true },
      consolidatedAt: { type: 'double', nullable: true },
    },
    {
      autoInc: true,
      indexes: [['ownerUserKey', 'reviewStatus', 'createdAt'], ['batchId'], ['contextKey', 'reviewStatus']],
    },
  );

  ctx.model.extend(
    'memory_fact',
    {
      id: 'unsigned',
      ownerUserKey: 'string',
      kind: 'string',
      topicKey: 'string',
      content: 'text',
      keywords: { type: 'text', nullable: true },
      importance: 'double',
      confidence: 'double',
      sensitivity: 'string',
      visibility: 'string',
      scopeType: { type: 'string', nullable: true },
      scopeKey: { type: 'string', nullable: true },
      memoryKey: { type: 'string', nullable: true },
      sourceKind: { type: 'string', nullable: true },
      sourceContextKey: 'string',
      targetSpeakerId: { type: 'string', nullable: true },
      targetSpeakerName: { type: 'string', nullable: true },
      evidenceMessageIds: { type: 'text', nullable: true },
      evidenceSpeakerIds: { type: 'text', nullable: true },
      attributionStatus: 'string',
      allowedContextKeys: { type: 'text', nullable: true },
      deniedContextKeys: { type: 'text', nullable: true },
      applicability: { type: 'text', nullable: true },
      validFrom: { type: 'double', nullable: true },
      validUntil: { type: 'double', nullable: true },
      expiresAt: { type: 'double', nullable: true },
      invalidatedAt: { type: 'double', nullable: true },
      retrievalText: { type: 'text', nullable: true },
      lastUsedReason: { type: 'text', nullable: true },
      firstSeenAt: 'double',
      lastSeenAt: 'double',
      lastAccessedAt: { type: 'double', nullable: true },
      embeddingModel: { type: 'string', nullable: true },
      embedding: { type: 'text', nullable: true },
      version: 'unsigned',
      archived: 'unsigned',
      supersedesId: { type: 'unsigned', nullable: true },
      conflictSetId: { type: 'string', nullable: true },
    },
    {
      autoInc: true,
      indexes: [
        ['ownerUserKey', 'archived'],
        ['ownerUserKey', 'scopeType', 'scopeKey', 'archived'],
        ['ownerUserKey', 'kind', 'topicKey', 'archived'],
        ['ownerUserKey', 'kind', 'topicKey', 'scopeType', 'scopeKey', 'archived'],
        ['ownerUserKey', 'visibility', 'sensitivity', 'archived'],
        ['memoryKey'],
        ['conflictSetId'],
        ['lastAccessedAt'],
      ],
    },
  );

  ctx.model.extend(
    'memory_episode',
    {
      id: 'unsigned',
      ownerUserKey: 'string',
      title: 'string',
      summary: 'text',
      keywords: { type: 'text', nullable: true },
      importance: 'double',
      confidence: 'double',
      sensitivity: 'string',
      visibility: 'string',
      scopeType: { type: 'string', nullable: true },
      scopeKey: { type: 'string', nullable: true },
      memoryKey: { type: 'string', nullable: true },
      sourceKind: { type: 'string', nullable: true },
      sourceContextKey: 'string',
      targetSpeakerId: { type: 'string', nullable: true },
      targetSpeakerName: { type: 'string', nullable: true },
      evidenceMessageIds: { type: 'text', nullable: true },
      evidenceSpeakerIds: { type: 'text', nullable: true },
      attributionStatus: 'string',
      allowedContextKeys: { type: 'text', nullable: true },
      deniedContextKeys: { type: 'text', nullable: true },
      applicability: { type: 'text', nullable: true },
      periodStart: { type: 'double', nullable: true },
      periodEnd: { type: 'double', nullable: true },
      validFrom: { type: 'double', nullable: true },
      validUntil: { type: 'double', nullable: true },
      expiresAt: { type: 'double', nullable: true },
      invalidatedAt: { type: 'double', nullable: true },
      retrievalText: { type: 'text', nullable: true },
      lastUsedReason: { type: 'text', nullable: true },
      firstSeenAt: 'double',
      lastSeenAt: 'double',
      lastAccessedAt: { type: 'double', nullable: true },
      embeddingModel: { type: 'string', nullable: true },
      embedding: { type: 'text', nullable: true },
      version: 'unsigned',
      archived: 'unsigned',
      supersedesId: { type: 'unsigned', nullable: true },
      conflictSetId: { type: 'string', nullable: true },
    },
    {
      autoInc: true,
      indexes: [
        ['ownerUserKey', 'archived'],
        ['ownerUserKey', 'scopeType', 'scopeKey', 'archived'],
        ['ownerUserKey', 'sourceContextKey', 'archived'],
        ['ownerUserKey', 'visibility', 'sensitivity', 'archived'],
        ['memoryKey'],
        ['periodStart'],
        ['lastAccessedAt'],
      ],
    },
  );

  ctx.model.extend(
    'memory_profile',
    {
      id: 'unsigned',
      ownerUserKey: 'string',
      profileKey: 'string',
      kind: 'string',
      content: 'text',
      valueJson: { type: 'text', nullable: true },
      importance: 'double',
      confidence: 'double',
      sensitivity: 'string',
      scopeType: 'string',
      scopeKey: { type: 'string', nullable: true },
      sourceContextKey: 'string',
      targetSpeakerId: { type: 'string', nullable: true },
      targetSpeakerName: { type: 'string', nullable: true },
      evidenceMessageIds: { type: 'text', nullable: true },
      evidenceSpeakerIds: { type: 'text', nullable: true },
      attributionStatus: 'string',
      allowedContextKeys: { type: 'text', nullable: true },
      deniedContextKeys: { type: 'text', nullable: true },
      validFrom: { type: 'double', nullable: true },
      validUntil: { type: 'double', nullable: true },
      expiresAt: { type: 'double', nullable: true },
      firstSeenAt: 'double',
      lastSeenAt: 'double',
      lastAccessedAt: { type: 'double', nullable: true },
      version: 'unsigned',
      archived: 'unsigned',
      supersedesId: { type: 'unsigned', nullable: true },
      conflictSetId: { type: 'string', nullable: true },
    },
    {
      autoInc: true,
      indexes: [
        ['ownerUserKey', 'archived'],
        ['ownerUserKey', 'kind', 'profileKey', 'archived'],
        ['ownerUserKey', 'scopeType', 'scopeKey', 'archived'],
      ],
    },
  );

  ctx.model.extend(
    'memory_session',
    {
      id: 'unsigned',
      sessionKey: 'string',
      ownerUserKey: 'string',
      contextKey: 'string',
      channelType: 'string',
      summary: 'text',
      workingStateJson: { type: 'text', nullable: true },
      startedAt: 'double',
      updatedAt: 'double',
      expiresAt: 'double',
      archived: 'unsigned',
    },
    {
      autoInc: true,
      indexes: [['sessionKey'], ['ownerUserKey', 'contextKey', 'archived'], ['expiresAt']],
    },
  );

  ctx.model.extend(
    'memory_source',
    {
      id: 'unsigned',
      sourceId: 'string',
      ownerUserKey: 'string',
      contextKey: 'string',
      conversationId: 'string',
      targetSpeakerId: 'string',
      targetSpeakerName: { type: 'string', nullable: true },
      messageIds: 'text',
      evidenceMessageIds: 'text',
      evidenceSpeakerIds: 'text',
      attributionStatus: 'string',
      roleWindowHash: 'string',
      excerpt: { type: 'text', nullable: true },
      redactedExcerpt: { type: 'text', nullable: true },
      createdAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['sourceId'], ['ownerUserKey', 'contextKey'], ['conversationId']],
    },
  );

  ctx.model.extend(
    'memory_provenance',
    {
      id: 'unsigned',
      ownerUserKey: 'string',
      contextKey: 'string',
      memoryType: 'string',
      memoryId: 'unsigned',
      candidateId: { type: 'unsigned', nullable: true },
      conversationId: { type: 'string', nullable: true },
      messageIds: { type: 'text', nullable: true },
      evidenceMessageIds: { type: 'text', nullable: true },
      evidenceSpeakerIds: { type: 'text', nullable: true },
      attributionStatus: 'string',
      source: 'string',
      createdAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['memoryType', 'memoryId'], ['ownerUserKey', 'contextKey'], ['conversationId']],
    },
  );

  ctx.model.extend(
    'memory_job',
    {
      id: 'unsigned',
      jobKey: 'string',
      jobType: 'string',
      status: 'string',
      payload: 'text',
      retryCount: 'unsigned',
      nextRunAt: 'double',
      lockedAt: { type: 'double', nullable: true },
      lastError: { type: 'text', nullable: true },
      createdAt: 'double',
      updatedAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['jobType', 'status', 'nextRunAt'], ['jobKey'], ['status', 'lockedAt']],
    },
  );

  ctx.model.extend(
    'memory_audit_event',
    {
      id: 'unsigned',
      userKey: { type: 'string', nullable: true },
      contextKey: { type: 'string', nullable: true },
      eventType: 'string',
      memoryType: { type: 'string', nullable: true },
      memoryId: { type: 'unsigned', nullable: true },
      candidateId: { type: 'unsigned', nullable: true },
      turnId: { type: 'string', nullable: true },
      detail: { type: 'text', nullable: true },
      createdAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['userKey', 'contextKey', 'createdAt'], ['eventType', 'createdAt'], ['turnId']],
    },
  );

  ctx.model.extend(
    'memory_tombstone',
    {
      id: 'unsigned',
      userKey: 'string',
      contextKey: { type: 'string', nullable: true },
      memoryType: 'string',
      memoryId: { type: 'unsigned', nullable: true },
      topicKey: { type: 'string', nullable: true },
      sourceMessageId: { type: 'string', nullable: true },
      reason: { type: 'text', nullable: true },
      createdAt: 'double',
    },
    {
      autoInc: true,
      indexes: [['userKey', 'memoryType', 'topicKey'], ['userKey', 'contextKey'], ['createdAt']],
    },
  );
}
